<a href="https://colab.research.google.com/github/TheKoray18/Regression-/blob/main/Regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regression 

In [2]:
class Regression():

  def fit(self,data_x,data_y):

    if data_x.shape == data_y.shape:
      
      #Eğim
      x_ort = np.mean(data_x)
      x_kare = 0
      y_ort = np.mean(data_y)
      xy_sum = 0
      n = len(data_x)
      self.result_eğim = 0
      up = 0
      down = 0

      for i in range(len(data_x)):

        xy_sum += np.multiply(data_x[i], data_y[i])
        x_kare += np.power(data_x[i], 2)
        
      up = np.subtract(xy_sum, np.multiply(n,(x_ort * y_ort)))
      down = np.subtract(x_kare, np.multiply(n,x_ort ** 2))
      self.result_eğim = np.divide(up,down) 
      
      #Sabit 
      self.result_sabit = 0
      x_ort = np.mean(data_x)
      y_ort = np.mean(data_y)
      eğim = self.result_eğim
      self.result_sabit = np.subtract(y_ort, np.multiply(self.result_eğim, x_ort))

      cache = {'Eğim':list(self.result_eğim),
               'Sabit':list(self.result_sabit)
               }
    else:
      print("data_x and data_y Shapes are not Same!")
    
    return cache

  def Prediction(self,data_test):
    
    self.reg_pred = []
    y = 0      
    for i in range(len(data_test)):
      y = np.add(self.result_sabit, np.multiply(self.result_eğim, data_test[i]))
      self.reg_pred.append(y)
    
    return self.reg_pred
  
  def Korelasyon(self,data_x,data_y):

    self.x_sum = 0
    self.x_kare = 0
    self.y_sum = 0
    self.y_kare = 0
    self.xy_sum = 0
    self.n = len(data_x)
    self.up = 0
    self.down = 0
    self.result_kor = 0

    for i in range(len(data_x)):

      self.x_sum += data_x[i]
      self.y_sum += data_y[i]
      self.xy_sum += np.multiply(data_x[i], data_y[i])
      self.x_kare += np.power(data_x[i], 2)
      self.y_kare += np.power(data_y[i], 2)

    self.up = np.subtract(self.xy_sum, np.divide(np.multiply(self.x_sum, self.y_sum), self.n))
    self.down = np.multiply(np.subtract(self.x_kare, np.divide(self.x_sum ** 2, self.n)), 
                            np.subtract(self.y_kare, np.divide(self.y_sum ** 2, self.n)))
    self.down = np.sqrt(self.down)
    self.result_kor = np.divide(self.up, self.down)

    return f"Korelasyon : {self.result_kor}" 
  
  def Varyans(self,data_x):
    
    self.ort_kare_top = 0
    self.ort = np.mean(data_x)
    self.payda = np.subtract(len(data_x),1)
    self.var_result = 0

    for i in range(len(data_x)):
      
      self.ort_kare_top += np.subtract(data_x[i], self.ort)**2

    self.var_result = np.divide(self.ort_kare_top,self.payda)

    return f"Variance:{self.var_result}"


# Regression Model For Test

In [3]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/column_2C_weka.csv')

data = df.copy()

data.head()

pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis     class
0         63.027818            22.552586  ...                 -0.254400  Abnormal
1         39.056951            10.060991  ...                  4.564259  Abnormal
2         68.832021            22.218482  ...                 -3.530317  Abnormal
3         69.297008            24.652878  ...                 11.211523  Abnormal
4         49.712859             9.652075  ...                  7.918501  Abnormal

[5 rows x 7 columns]

In [6]:
data['class'] = [1 if i == 'Abnormal' else 0 for i in data['class']]

data.head()

pelvic_incidence  pelvic_tilt numeric  ...  degree_spondylolisthesis  class
0         63.027818            22.552586  ...                 -0.254400      1
1         39.056951            10.060991  ...                  4.564259      1
2         68.832021            22.218482  ...                 -3.530317      1
3         69.297008            24.652878  ...                 11.211523      1
4         49.712859             9.652075  ...                  7.918501      1

[5 rows x 7 columns]

In [7]:
pelvic = data['pelvic_incidence'].values

sacral = data['sacral_slope'].values

In [8]:
pelvic = np.array([pelvic]).reshape(310,1)
sacral = np.array([sacral]).reshape(310,1)

In [9]:
from sklearn.linear_model import LinearRegression

def linear_model(data_x,data_y):
  
  lr_mod = LinearRegression()
  model = lr_mod.fit(data_x,data_y)
  y_pred = model.predict(data_y)

  cache = {'model':model,
          'y_pred':y_pred,
           }
  return cache

In [10]:
cache = linear_model(pelvic,sacral)

model,y_pred= cache['model'],cache['y_pred']

- Modelimizin Sabit(Constant)'ini bulalım

In [11]:
const = model.intercept_

const

array([4.55916137])

- Modelimizin Eğim(Slope)'ini bulalım

In [12]:
slope = model.coef_

slope

array([[0.63465775]])

- Modelimizi kullanarak tahmin yapalım 

In [13]:
model.predict([[45]])

array([[33.11876009]])

- Denklem ile bulalım bu tahmini

- İlk önce Sabit ve Eğimi Bulacağız

- Ho = 0o + 01.Xi

- Maliyet Fonksiyonu : Basitçe diyebiliriz ki bulduğumuz hipotez ile var olan gerçek değerler arasındaki fark bizim maliyet fonksiyonumuzdur. Yani hipotezimizin bize olan maliyetini ölçmemizi sağlar.

In [14]:
y_head = const + slope * 45

y_head

array([[33.11876009]])

In [15]:
np.var(pelvic)

296.1392533400351

# Our Regression Model For Test

In [16]:
out_reg = Regression()

In [17]:
out_reg.fit(pelvic,sacral)

{'Eğim': [0.6346577494130035], 'Sabit': [4.559161366153063]}

In [21]:
our_y_pred = out_reg.Prediction(sacral)

our_y_pred

[array([30.24708072]),
 array([22.96167177]),
 array([34.14280508]),
 array([32.89290454]),
 array([29.98404867]),
 array([21.26861662]),
 array([28.40235943]),
 array([26.52539097]),
 array([23.76164368]),
 array([24.66224307]),
 array([27.82929106]),
 array([13.13755606]),
 array([22.93313483]),
 array([25.57353113]),
 array([25.57353113]),
 array([24.72916541]),
 array([32.14930423]),
 array([22.4129358]),
 array([20.58627721]),
 array([23.26626274]),
 array([23.43698079]),
 array([26.04683869]),
 array([29.09490826]),
 array([25.16725519]),
 array([13.04258752]),
 array([21.99602231]),
 array([14.32557173]),
 array([21.74066688]),
 array([18.91503395]),
 array([31.20667116]),
 array([27.03686996]),
 array([26.96969662]),
 array([22.00770339]),
 array([20.85515142]),
 array([22.07399905]),
 array([19.5738925]),
 array([20.49009186]),
 array([14.87882629]),
 array([21.6922794]),
 array([25.76169613]),
 array([19.65816037]),
 array([28.70601175]),
 array([26.5336497]),
 array([29.9185

- Kendi Regression modelimiz ile **45** değerini tahmin edelim. 
- Sonuç **LinearRegression()** modeli ile aynı sonuç olduğunu gördük.

In [20]:
out_reg.Prediction([[45]])

[array([33.11876009])]

In [19]:
out_reg.Varyans(pelvic)

'Variance:[297.0976328]'